name: Node-6 CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [6.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
    - name: build
      run: npm run build --if-present
    - name: test
      run: npm test
      env:
        CI: true
    - name: codecov
      run: npm run codecov
      env:
        CODECOV_TOKEN: 2efe2a74-64f6-40d2-a2dd-c91db03f2db2
